language: c

compiler: gcc

services:
    - docker

stages:
    - build
    - tests

jobs:
    include:
      - stage: build
        before_script:
          - docker pull epitechcontent/epitest-docker
        script: 
          - docker run -v $PWD:/usr/local/bugs epitechcontent/epitest-docker bash -c "cd /usr/local/bugs && make"
      - stage: tests
        before_script:
          - docker pull epitechcontent/epitest-docker
        script:
          - docker run -v $PWD:/usr/local/bugs epitechcontent/epitest-docker bash -c "cd /usr/local/bugs && make tests_run
