language: c

compiler: gcc

services:
    - docker

jobs:
    include:
      - stage: build
        before_script:
          - docker pull epitechcontent/epitest-docker
        script: 
          - docker run -v $PWD:/usr/local/bugs bash -c "cd /usr/local/bugs && make"
