language: c

compiler: gcc

services:
    - docker

jobs:
    include:
      - stage: build
        install:
          - docker pull epitechcontent/epitest-docker
        script: 
          - docker run -v `pwd`:/usr/local/bugs bash -c "cd /usr/local/bugs;make"
