name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: "MAKE"
        run: |
          make
        
