name: C/C++ CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "MAKE"
        uses: .github/actions/epitest-docker-action@master
        
