name: C/C++ CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@master
      - name: "make"
        uses: ./.github/actions/epitest-docker-action@master
        
